name: My first gha

on:
  pull_request:
    types: [closed]
    branches: [ master ]
    paths: [.chart-rcp/**]

jobs:
  my-first-job:
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        node-version: ['14.x']

    steps:
      - name: Set up Git repository
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        if: github.event.pull_request.merged == true
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Printing github base ref
        run: echo ${{ github.base_ref}}

      - name: Printing github workspace
        run: echo ${{ github.workspace}}

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v29.0.2
           
      - name: List all added files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was added"
          done
      # - name: Installing dependencies
      #   if: github.event.pull_request.merged == true
      #   run: yarn install

      # - name: Executing a script
      #   if: github.event.pull_request.merged == true
      #   run: yarn update:helm-chart

      

      # - name: Upgrading patch version
      #   if: github.event.pull_request.merged == true
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     add: '--all'
      #     message: 'upgrade: patch version upgrade'