name: My first gha

on:
  pull_request:
    types: [closed]
    branches: [ master ]
    paths: [.chart-rcp/**]

jobs:
  my-first-job:
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        node-version: ['14.x']

    steps:
      - name: Set up Git repository
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        if: github.event.pull_request.merged == true
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Printing github base ref
        run: echo ${{ github.base_ref}}
           
      - name: Installing dependencies
        if: github.event.pull_request.merged == true
        run: yarn install

      - name: Executing a script
        if: github.event.pull_request.merged == true
        run: yarn update:helm-chart

      # - name: Upgrading patch version
      #   if: github.event.pull_request.merged == true
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     add: '--all'
      #     message: 'upgrade: patch version upgrade'