name: My first gha

on:
  pull_request:
    types: [closed]
    branches: [ master ]
    paths: [.chart-rcp/**]

jobs:
  my-first-job:
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        node-version: ['14.x']

    steps:
      - name: Set up Git repository
        if: github.event.pull_request == true
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        if: github.event.pull_request == false
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}