name: My first gha

on:
  push:
    branches: [ master ]
    paths: [.chart-rcp/**]

jobs:
  my-first-job:
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        node-version: ['14.x']

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Executing a script
        run: yarn update:helm-chart