name: My first gha

on:
  pull_request:
    types: [closed]
    branches: [ master ]
    paths: [.chart-rcp/**]

jobs:
  my-first-job:
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        node-version: ['14.x']

    steps:
      - name: Set up Git repository
        if: github.event.pull_request.merged == true
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        if: github.event.pull_request.merged == true
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
           
      - name: Installing dependencies
        if: github.event.pull_request.merged == true
        run: yarn install

      - name: Executing a script
        if: github.event.pull_request.merged == true
        run: yarn update:helm-chart

      - name: Upgrading patch version
        if: github.event.pull_request.merged == true
        uses: actions-js/push@master
        with:
          message: 'upgrade: patch version upgrade'
          branch: master